{% set name = "bfio" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PolusAI/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ad92d5755f7a97f1c040179929038fecd58a16f802d35736de9a9c3ba55ebca6
  patches:
    - numpy_2.patch
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - imagecodecs >=2021.2.26
    - jpype1
    - numpy >=1.20.1
    - ome-types >=0.4.2
    - pip
    - python >=3.8
    - scyjava
    - tifffile >=2021.8.30
    - zarr >=2.6.1
    - bfiocpp
  run:
    - imagecodecs >=2021.2.26
    - jpype1
    - numpy >=1.20.1
    - ome-types >=0.4.2
    - python >=3.8
    - scyjava
    - tifffile >=2021.8.30
    - zarr >=2.6.1
    - bfiocpp

test:
  imports:
    - bfio
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/bfio/
  summary: Simple reading and writing classes for tiled tiffs using Bioformats.
  dev_url: https://github.com/PolusAI/bfio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Nicholas-Schaub
    - sameeul
    - goanpeca
    - jaimergp
