{% set name = "bfio" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PolusAI/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f39f2a3a149814012380949b5f10f3012539f29fa77fe06d45b3fc41762686dc
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - imagecodecs >=2021.2.26
    - numpy >=1.20.1
    - ome-types >=0.4.2
    - python >=3.8
    - tifffile >=2021.8.30

test:
  imports:
    - bfio
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/bfio/
  summary: Simple reading and writing classes for tiled tiffs using Bioformats.
  dev_url: https://github.com/PolusAI/bfio  
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Nicholas-Schaub
    - sameeul
    - goanpeca
    - jaimergp
