{% set name = "bfio" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PolusAI/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2ecc426331323aec9bd4cc66f4fad21dd6ada7950de756d07c1da1ac5257f991
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - imagecodecs >=2021.2.26
    - lxml
    - numpy >=1.20.1
    - ome-types >=0.2.10
    - python >=3.6
    - tifffile >=2021.8.30

test:
  imports:
    - bfio
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - napari

about:
  home: https://pypi.org/project/bfio/
  summary: Simple reading and writing classes for tiled tiffs using Bioformats.
  dev_url: https://github.com/PolusAI/bfio  
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Nicholas-Schaub
    - goanpeca
    - jaimergp
